// accont sql
var acd;
var chatUserName = "imię";
var userID;
var chatsMessages = ["last message", "last message from user2", "last message from user3"];
var avatarFile = ["0-avatar.png", "1-avatar.png", "2-avatar.png"]; // temporary
let friendlistId = [];
let friendlistLogins = [];



/* TODO:
    loading chats with friends from files named: [friend_id]-chat.json
    if user sended message add to files named: [friend_id]-chat.json
    load avatars
    if user click on friend box in friend list clear chatStory and fill messages from file contain messages
*/


// get ids and logins friends from json generated by php and add to arrays
function getFriendList() {
    fetch('data/friendlist.json')
        .then(response => response.json())
        .then(data => {
            friendlistId = data.map(Number);
        })
        .catch(error => {
            console.error('Błąd odczytu pliku:', error);
        });

    fetch('data/friendLogins.json')
        .then(response => response.json())
        .then(data => {
            friendlistLogins = data;
            loadFriendList();
        })
        .catch(error => {
            console.error('Wystąpił błąd:', error);
        });

}
getFriendList();

// load and print friends logins and in future avatars
function loadFriendList() {
    for (let i = 0; i != friendlistId.length; i++) {
        let id = document.getElementById(i);
        id = i;
        let avatarName = 'avatar' + i;
        document.getElementById('chatList').innerHTML += "<div id=\"" + friendlistId[i] + "\" class=\"chatArticle\"><div id=\"" + avatarName + "\" class=\"chatAvatar\"></div><div class=\"chatValue\"><div class=\"chatName\">" + friendlistLogins[i] + "</div><div class=\"chatLastMessage\">" + chatsMessages[i] + "</div></div>";
        var elem = document.createElement("img");
        document.getElementById(avatarName).appendChild(elem);
        elem.src = "src/users avatars/" + i + "-avatar.png";
        elem.style.height = "100px";
        elem.style.width = "100px";
        elem.style.borderRadius = "50%";
    }
    const chatBox = document.querySelectorAll('.chatArticle');
    chatBox.forEach(box => {
        box.addEventListener('click', function handleClick(event) {
            const x = document.getElementById('chatStory');
            x.style.display = "flex";
        });
    });
}













function printAvatarInList() {
    // in progress
}


printAvatarInList();
